import cvxportfolio as cvx



SET = ['AAV.BK', 'ACC.BK', 'ADB.BK', 'ADVANC.BK', 'AE.BK', 'AF.BK',
       'AGE.BK', 'AI.BK', 'AIT.BK', 'AJA.BK', 'AKP.BK', 'AKR.BK',
       'AKS.BK', 'ALLA.BK', 'ALPHAX.BK', 'ALT.BK', 'AMANAH.BK',
       'AMATA.BK', 'ANAN.BK', 'AOT.BK', 'AP.BK', 'APURE.BK', 'AQUA-R.BK',
       'AQUA.BK', 'ARIP.BK', 'AS.BK', 'ASAP.BK', 'ASIAN.BK', 'ASP.BK',
       'ATP30.BK', 'AU.BK', 'AUCT.BK', 'B.BK', 'BA.BK', 'BANPU-R.BK',
       'BANPU.BK', 'BBL.BK', 'BCH-R.BK', 'BCH.BK', 'BCP.BK', 'BCPG.BK',
       'BDMS.BK', 'BEAUTY-R.BK', 'BEAUTY.BK', 'BEC.BK', 'BEM.BK',
       'BGRIM.BK', 'BGT.BK', 'BH.BK', 'BIG.BK', 'BIOTEC.BK', 'BJC.BK',
       'BLA.BK', 'BLAND.BK', 'BM.BK', 'BPP.BK', 'BR.BK', 'BSBM.BK',
       'BTS.BK', 'BWG.BK', 'BYD.BK', 'CBG.BK', 'CCET.BK', 'CCP.BK',
       'CEN.BK', 'CENTEL.BK', 'CFRESH.BK', 'CGD.BK', 'CGH.BK', 'CHEWA.BK',
       'CHG-R.BK', 'CHG.BK', 'CHO.BK', 'CI.BK', 'CIG.BK', 'CIMBT.BK',
       'CK.BK', 'CKP.BK', 'CMO.BK', 'COM7.BK', 'CPALL-R.BK', 'CPALL.BK',
       'CPF.BK', 'CPI.BK', 'CPN.BK', 'CPT.BK', 'CRANE.BK', 'CRD.BK',
       'CSS.BK', 'CWT.BK', 'DCC.BK', 'DCON.BK', 'DELTA.BK', 'DEMCO.BK',
       'DIMET.BK', 'EA-R.BK', 'EA.BK', 'ECF.BK', 'ECL.BK', 'EE.BK',
       'EFORL.BK', 'EKH.BK', 'EMC.BK', 'EP.BK', 'EPG.BK', 'ERW.BK',
       'ESTAR.BK', 'ETE.BK', 'EVER.BK', 'FANCY.BK', 'FN.BK', 'FSMART.BK',
       'FVC.BK', 'GBX.BK', 'GCAP.BK', 'GEL.BK', 'GENCO.BK', 'GFPT.BK',
       'GIFT.BK', 'GJS.BK', 'GLAND.BK', 'GLOBAL-R.BK', 'GLOBAL.BK',
       'GLOCON.BK', 'GPSC.BK', 'GRAND.BK', 'GREEN.BK', 'GTV.BK',
       'GULF.BK', 'GUNKUL-R.BK', 'GUNKUL.BK', 'HANA.BK', 'HMPRO.BK',
       'HPT.BK', 'HUMAN.BK', 'ICHI.BK', 'ICN.BK', 'III.BK', 'INET.BK',
       'INGRS.BK', 'INOX.BK', 'INTUCH.BK', 'IRCP.BK', 'IRPC.BK', 'ITD.BK',
       'ITEL.BK', 'IVL-R.BK', 'IVL.BK', 'J.BK', 'JAS.BK', 'JCK.BK',
       'JCKH.BK', 'JMART.BK', 'JMT.BK', 'K.BK', 'KAMART.BK', 'KBANK.BK',
       'KCE-R.BK', 'KCE.BK', 'KCM.BK', 'KGEN.BK', 'KGI.BK', 'KIAT.BK',
       'KKP.BK', 'KOOL.BK', 'KSL.BK', 'KTB-R.BK', 'KTB.BK', 'KTC.BK',
       'KWI.BK', 'LDC.BK', 'LH-R.BK', 'LH.BK', 'LHFG.BK', 'LOXLEY.BK',
       'LPN.BK', 'MAJOR.BK', 'MBK.BK', 'MEGA.BK', 'META.BK', 'MIDA.BK',
       'MILL.BK', 'MINT-R.BK', 'MINT.BK', 'ML.BK', 'MONO.BK', 'MOONG.BK',
       'MORE.BK', 'MTC.BK', 'NATION.BK', 'NCH.BK', 'NCL.BK', 'NEWS-R.BK',
       'NEX.BK', 'NOBLE.BK', 'NUSA-R.BK', 'NUSA.BK', 'NWR.BK', 'NYT.BK',
       'ORI.BK', 'PAF.BK', 'PERM.BK', 'PF-R.BK', 'PF.BK', 'PIMO.BK',
       'PJW.BK', 'PK.BK', 'PLANB-R.BK', 'PLANB.BK', 'PLANET.BK', 'PLE.BK',
       'PORT.BK', 'PPS.BK', 'PRIME.BK', 'PRINC.BK', 'PRM.BK', 'PSG.BK',
       'PSL.BK', 'PSTC.BK', 'PTG.BK', 'PTL.BK', 'PTT-R.BK', 'PTT.BK',
       'PTTEP.BK', 'PTTGC-R.BK', 'PTTGC.BK', 'QH-R.BK', 'QH.BK',
       'RABBIT-R.BK', 'RABBIT.BK', 'RATCH.BK', 'RCL.BK', 'RICHY.BK',
       'RML.BK', 'ROCTEC.BK', 'ROJNA.BK', 'RPC.BK', 'RS.BK', 'RWI.BK',
       'S.BK', 'SAMART.BK', 'SAMCO.BK', 'SANKO.BK', 'SAWAD.BK', 'SC.BK',
       'SCAP.BK', 'SCB-R.BK', 'SCC.BK', 'SCI.BK', 'SCN.BK', 'SE.BK',
       'SEAFCO.BK', 'SEAOIL.BK', 'SELIC.BK', 'SGF.BK', 'SGP.BK',
       'SIMAT.BK', 'SINGER.BK', 'SIRI-R.BK', 'SIRI.BK', 'SITHAI.BK',
       'SJWD.BK', 'SKE.BK', 'SMART.BK', 'SMT.BK', 'SOLAR.BK', 'SPA.BK',
       'SPACK.BK', 'SPALI.BK', 'SPRC-R.BK', 'SPRC.BK', 'SPVI.BK', 'SQ.BK',
       'SSP.BK', 'STA.BK', 'STEC.BK', 'STOWER.BK', 'STPI.BK', 'SUN.BK',
       'SUPER.BK', 'SUSCO.BK', 'SVI.BK', 'SVOA.BK', 'SYNEX.BK',
       'SYNTEC.BK', 'TACC.BK', 'TAKUNI.BK', 'TASCO.BK', 'TCAP.BK',
       'TCC.BK', 'TCMC.BK', 'TEAM.BK', 'TFG.BK', 'TFI.BK', 'TGPRO.BK',
       'TH.BK', 'THANA.BK', 'THANI-R.BK', 'THANI.BK', 'THCOM.BK',
       'THE.BK', 'THMUI.BK', 'THRE.BK', 'THREL.BK', 'TISCO.BK',
       'TITLE.BK', 'TKN.BK', 'TKS.BK', 'TKT.BK', 'TMC.BK', 'TMI.BK',
       'TNDT.BK', 'TNPC.BK', 'TOA.BK', 'TOP.BK', 'TPIPL.BK', 'TPIPP.BK',
       'TPOLY.BK', 'TRC.BK', 'TRITN.BK', 'TRUBB.BK', 'TRUE-R.BK',
       'TRUE.BK', 'TSE.BK', 'TSI.BK', 'TSTH.BK', 'TTA.BK', 'TTB.BK',
       'TTCL.BK', 'TTW.BK', 'TU-R.BK', 'TU.BK', 'TVDH.BK', 'TVT.BK',
       'TWZ-R.BK', 'TWZ.BK', 'UEC.BK', 'UKEM.BK', 'UMI.BK', 'UNIQ.BK',
       'UREKA.BK', 'UV.BK', 'VCOM.BK', 'VGI-R.BK', 'VGI.BK', 'VIBHA.BK',
       'VPO.BK', 'W.BK', 'WAVE.BK', 'WHA-R.BK', 'WHA.BK', 'WHAUP.BK',
       'WICE.BK', 'WIIK.BK', 'WIN.BK', 'WORK.BK', 'WPH.BK', 'XO.BK',
       'XPG.BK', 'ZIGA.BK']


if __name__ =='__main__':
    simulator = cvx.StockMarketSimulator(['AAV.BK', 'ACC.BK', 'ADB.BK', 'ADVANC.BK'])